// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	activityTblFieldNames          = builder.RawFieldNames(&ActivityTbl{})
	activityTblRows                = strings.Join(activityTblFieldNames, ",")
	activityTblRowsExpectAutoSet   = strings.Join(stringx.Remove(activityTblFieldNames), ",")
	activityTblRowsWithPlaceHolder = strings.Join(stringx.Remove(activityTblFieldNames, "`id`"), "=?,") + "=?"
)

type (
	activityTblModel interface {
		Insert(ctx context.Context, data *ActivityTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ActivityTbl, error)
		Update(ctx context.Context, data *ActivityTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultActivityTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ActivityTbl struct {
		Id          int64          `db:"id"`
		TourId      sql.NullInt64  `db:"tour_id"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		CreatedAt   sql.NullInt64  `db:"created_at"`
		UpdatedAt   sql.NullInt64  `db:"updated_at"`
	}
)

func newActivityTblModel(conn sqlx.SqlConn) *defaultActivityTblModel {
	return &defaultActivityTblModel{
		conn:  conn,
		table: "`activity_tbl`",
	}
}

func (m *defaultActivityTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultActivityTblModel) FindOne(ctx context.Context, id int64) (*ActivityTbl, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", activityTblRows, m.table)
	var resp ActivityTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActivityTblModel) Insert(ctx context.Context, data *ActivityTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, activityTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TourId, data.Name, data.Description, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultActivityTblModel) Update(ctx context.Context, data *ActivityTbl) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, activityTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TourId, data.Name, data.Description, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultActivityTblModel) tableName() string {
	return m.table
}
