// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	journeyTblFieldNames          = builder.RawFieldNames(&JourneyTbl{})
	journeyTblRows                = strings.Join(journeyTblFieldNames, ",")
	journeyTblRowsExpectAutoSet   = strings.Join(stringx.Remove(journeyTblFieldNames), ",")
	journeyTblRowsWithPlaceHolder = strings.Join(stringx.Remove(journeyTblFieldNames, "`id`"), "=?,") + "=?"
)

type (
	journeyTblModel interface {
		Insert(ctx context.Context, data *JourneyTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*JourneyTbl, error)
		Update(ctx context.Context, data *JourneyTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultJourneyTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	JourneyTbl struct {
		Id          int64          `db:"id"`
		TourId      sql.NullInt64  `db:"tour_id"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		CreatedAt   sql.NullInt64  `db:"created_at"`
		UpdatedAt   sql.NullInt64  `db:"updated_at"`
	}
)

func newJourneyTblModel(conn sqlx.SqlConn) *defaultJourneyTblModel {
	return &defaultJourneyTblModel{
		conn:  conn,
		table: "`journey_tbl`",
	}
}

func (m *defaultJourneyTblModel) withSession(session sqlx.Session) *defaultJourneyTblModel {
	return &defaultJourneyTblModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`journey_tbl`",
	}
}

func (m *defaultJourneyTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultJourneyTblModel) FindOne(ctx context.Context, id int64) (*JourneyTbl, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", journeyTblRows, m.table)
	var resp JourneyTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJourneyTblModel) Insert(ctx context.Context, data *JourneyTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, journeyTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TourId, data.Name, data.Description, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultJourneyTblModel) Update(ctx context.Context, data *JourneyTbl) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, journeyTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TourId, data.Name, data.Description, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultJourneyTblModel) tableName() string {
	return m.table
}
