// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	requestTblFieldNames          = builder.RawFieldNames(&RequestTbl{})
	requestTblRows                = strings.Join(requestTblFieldNames, ",")
	requestTblRowsExpectAutoSet   = strings.Join(stringx.Remove(requestTblFieldNames), ",")
	requestTblRowsWithPlaceHolder = strings.Join(stringx.Remove(requestTblFieldNames, "`id`"), "=?,") + "=?"
)

type (
	requestTblModel interface {
		Insert(ctx context.Context, data *RequestTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RequestTbl, error)
		Update(ctx context.Context, data *RequestTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRequestTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RequestTbl struct {
		Id          int64          `db:"id"`
		UserId      sql.NullInt64  `db:"user_id"`
		UserName    string         `db:"user_name"`
		Phone       string         `db:"phone"`
		Description sql.NullString `db:"description"`
		ProductId   sql.NullInt64  `db:"product_id"`
		Status      int64          `db:"status"`
		CreatedAt   sql.NullInt64  `db:"created_at"`
		UpdatedAt   sql.NullInt64  `db:"updated_at"`
	}
)

func newRequestTblModel(conn sqlx.SqlConn) *defaultRequestTblModel {
	return &defaultRequestTblModel{
		conn:  conn,
		table: "`request_tbl`",
	}
}

func (m *defaultRequestTblModel) withSession(session sqlx.Session) *defaultRequestTblModel {
	return &defaultRequestTblModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`request_tbl`",
	}
}

func (m *defaultRequestTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRequestTblModel) FindOne(ctx context.Context, id int64) (*RequestTbl, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", requestTblRows, m.table)
	var resp RequestTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRequestTblModel) Insert(ctx context.Context, data *RequestTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, requestTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.UserName, data.Phone, data.Description, data.ProductId, data.Status, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultRequestTblModel) Update(ctx context.Context, data *RequestTbl) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, requestTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserName, data.Phone, data.Description, data.ProductId, data.Status, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultRequestTblModel) tableName() string {
	return m.table
}
