// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	templateTblFieldNames          = builder.RawFieldNames(&TemplateTbl{})
	templateTblRows                = strings.Join(templateTblFieldNames, ",")
	templateTblRowsExpectAutoSet   = strings.Join(stringx.Remove(templateTblFieldNames), ",")
	templateTblRowsWithPlaceHolder = strings.Join(stringx.Remove(templateTblFieldNames, "`id`"), "=?,") + "=?"
)

type (
	templateTblModel interface {
		Insert(ctx context.Context, data *TemplateTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TemplateTbl, error)
		Update(ctx context.Context, data *TemplateTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTemplateTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TemplateTbl struct {
		Id          int64          `db:"id"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		Location    sql.NullInt64  `db:"location"`
		NumberDay   sql.NullInt64  `db:"number_day"`
		Overview    sql.NullString `db:"overview"`
		CreatedAt   sql.NullInt64  `db:"created_at"`
		UpdatedAt   sql.NullInt64  `db:"updated_at"`
		CreatedBy   sql.NullInt64  `db:"created_by"`
		UpdatedBy   sql.NullInt64  `db:"updated_by"`
	}
)

func newTemplateTblModel(conn sqlx.SqlConn) *defaultTemplateTblModel {
	return &defaultTemplateTblModel{
		conn:  conn,
		table: "`template_tbl`",
	}
}

func (m *defaultTemplateTblModel) withSession(session sqlx.Session) *defaultTemplateTblModel {
	return &defaultTemplateTblModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`template_tbl`",
	}
}

func (m *defaultTemplateTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTemplateTblModel) FindOne(ctx context.Context, id int64) (*TemplateTbl, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", templateTblRows, m.table)
	var resp TemplateTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTemplateTblModel) Insert(ctx context.Context, data *TemplateTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, templateTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Description, data.Location, data.NumberDay, data.Overview, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy)
	return ret, err
}

func (m *defaultTemplateTblModel) Update(ctx context.Context, data *TemplateTbl) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, templateTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Location, data.NumberDay, data.Overview, data.CreatedAt, data.UpdatedAt, data.CreatedBy, data.UpdatedBy, data.Id)
	return err
}

func (m *defaultTemplateTblModel) tableName() string {
	return m.table
}
