// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userTblFieldNames          = builder.RawFieldNames(&UserTbl{})
	userTblRows                = strings.Join(userTblFieldNames, ",")
	userTblRowsExpectAutoSet   = strings.Join(stringx.Remove(userTblFieldNames), ",")
	userTblRowsWithPlaceHolder = strings.Join(stringx.Remove(userTblFieldNames, "`id`"), "=?,") + "=?"
)

type (
	userTblModel interface {
		Insert(ctx context.Context, data *UserTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserTbl, error)
		Update(ctx context.Context, data *UserTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserTbl struct {
		Id           int64          `db:"id"`
		Email        string         `db:"email"`
		FullName     sql.NullString `db:"full_name"`
		PasswordHash string         `db:"password_hash"`
		Role         int64          `db:"role"`
		Status       int64          `db:"status"`
		CreatedAt    sql.NullInt64  `db:"created_at"`
		UpdatedAt    sql.NullInt64  `db:"updated_at"`
	}
)

func newUserTblModel(conn sqlx.SqlConn) *defaultUserTblModel {
	return &defaultUserTblModel{
		conn:  conn,
		table: "`user_tbl`",
	}
}

func (m *defaultUserTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserTblModel) FindOne(ctx context.Context, id int64) (*UserTbl, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTblRows, m.table)
	var resp UserTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTblModel) Insert(ctx context.Context, data *UserTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Email, data.FullName, data.PasswordHash, data.Role, data.Status, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultUserTblModel) Update(ctx context.Context, data *UserTbl) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Email, data.FullName, data.PasswordHash, data.Role, data.Status, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultUserTblModel) tableName() string {
	return m.table
}
