// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"da-tour/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/message",
				Handler: SendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tour/filter",
				Handler: SearchTourHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tour/:tourID",
				Handler: TourDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/user/:userID",
					Handler: UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tour",
					Handler: CreateTourHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/tour/:tourID",
					Handler: UpdateTourHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order",
					Handler: CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/order/:orderID",
					Handler: GetOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/order/filter",
					Handler: FilterOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/order/:orderID/status",
					Handler: UpdateOrderStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/order/:orderID",
					Handler: UpdateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/payment",
					Handler: CreatePaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/payment/filter",
					Handler: FilterPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/payment/:paymentID",
					Handler: UpdatePaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/payment/:paymentID",
					Handler: DeletePaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/payment/:paymentID/status",
					Handler: UpdatePaymentStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/"),
	)
}
