const actionTypes = {
    LOGIN: "LOGIN",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    GET_CURRENT_USER: "GET_CURRENT_USER",
    UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
    UPDATE_CURRENT_USER_SUCCESS: "UPDATE_CURRENT_USER_SUCCESS",
    UPDATE_CURRENT_USER_FAIL: "UPDATE_CURRENT_USER_FAIL",
    SET_CURRENTPAGE: "SET_CURRENTPAGE",
  };
  
  export default actionTypes;
  