package common

// RESPONSE_CODE_AND_MESSAGE

const (
	SUCCESS_CODE = 0
	SUCCESS_MESS = "Success"

	DB_ERR_CODE = 1
	DB_ERR_MESS = "Database error"

	UNKNOWN_ERR_CODE = 2
	UNKNOWN_ERR_MESS = "Unknown error"

	INVALID_REQUEST_CODE = 3
	INVALID_REQUEST_MESS = "Invalid request"

	NOT_FOUND_CODE = 4
	NOT_FOUND_MESS = "Not found"
)

const (
	USER_NOT_FOUND_CODE = 2000
	USER_NOT_FOUND_MESS = "User not found"

	INVALID_PASSWORD_CODE = 2001
	INVALID_PASSWORD_MESS = "Invalid password"

	USER_NOT_ACTIVE_CODE = 2002
	USER_NOT_ACTIVE_MESS = "User not active"

	EMAIL_ALREADY_REGISTERED_CODE = 2003
	EMAIL_ALREADY_REGISTERED_MESS = "Email already registered"
)

const (
	TOUR_NOT_ENOUGH_CODE = 3000
	TOUR_NOT_ENOUGH_MESS = "Tour not enough"
)

// CONST

const (
	USER_ROLE_GUEST = 0
	USER_ROLE_ADMIN = 1
	USER_ROLE_USER  = 2

	USER_STATUS_INACTIVE = 0
	USER_STATUS_ACTIVE   = 1
)

// TOUR_STATUS
const (
	TOUR_STATUS_ACTIVE   = 1
	TOUR_STATUS_INACTIVE = 2
	TOUR_STATUS_SOLD_OUT = 3
)

// ORDER_STATUS
const (
	ORDER_STATUS_PENDING   = 1
	ORDER_STATUS_CONFIRMED = 2
	ORDER_STATUS_CANCELLED = 3
	ORDER_STATUS_COMPLETED = 4
)

// PAYMENT_STATUS
const (
	PAYMENT_STATUS_PENDING   = 1
	PAYMENT_STATUS_COMPLETED = 2
	PAYMENT_STATUS_REFUNDED  = 3
)
