// Code generated by goctl. DO NOT EDIT.
package types

type Result struct {
	Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
	Message string `json:"message"` // Result message: detail response code
}

type User struct {
	UserID   int64  `json:"userID"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Role     int64  `json:"role"`
	Status   int64  `json:"status"`
}

type Tour struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	Description   string      `json:"description"`
	Duration      int64       `json:"duration"`
	Location      int64       `json:"location"`
	Overview      string      `json:"overview"`
	Activities    []Activity  `json:"activities"`
	Services      []Service   `json:"services"`
	Itineraries   []Itinerary `json:"itineraries"`
	Price         float64     `json:"price"`
	DepartureDate int64       `json:"departureDate"`
	Quantity      int64       `json:"quantity"`
	Remain        int64       `json:"remain"`
	Status        int64       `json:"status"`
}

type Activity struct {
	ID     int64  `json:"id"`
	Title  string `json:"title"`
	Detail string `json:"detail"`
}

type Service struct {
	ID     int64  `json:"id"`
	Title  string `json:"title"`
	Detail string `json:"detail"`
}

type Itinerary struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type LoginReq struct {
	Email    string `form:"email"`    // user_name
	Password string `form:"password"` //  password
}

type LoginRes struct {
	Result Result `json:"result"`
	Token  string `json:"token"` // jwt token for api
	User   User   `json:"user"`  // Account info
}

type RegisterReq struct {
	Fullname string `form:"fullname"`
	Email    string `form:"email"`
	Password string `form:"password"`
}

type RegisterRes struct {
	Result Result `json:"result"`
	Token  string `json:"token"` // jwt token for api
	User   User   `json:"user"`  // Account info
}

type UpdateUserReq struct {
}

type UpdateUserRes struct {
}

type SendMessageReq struct {
}

type SendMessageRes struct {
}

type SearchTourReq struct {
	Location      int64 `form:"location"`
	DepartureDate int64 `form:"departureDate"`
	Limit         int64 `form:"limit"`
	Offset        int64 `form:"offset"`
}

type SearchTourRes struct {
	Tours  []Tour `json:"tours"`
	Total  int64  `json:"total"`
	Result Result `json:"result"`
}

type TourDetailReq struct {
	TourID int64 `path:"tourID"`
}

type TourDetailRes struct {
	Tour   Tour   `json:"tour"`
	Result Result `json:"result"`
}

type CreateTourReq struct {
	Image         string  `form:"image"`
	Name          string  `form:"name"`
	Description   string  `form:"description"`
	Duration      int64   `form:"duration"`
	Location      int64   `form:"location"`
	Overview      string  `form:"overview"`
	Activities    string  `form:"activities"`
	Services      string  `form:"services"`
	Itinerary     string  `form:"itinerary"`
	Price         float64 `form:"price"`
	Seats         int64   `form:"seats"`
	DepartureDate int64   `form:"departureDate"`
}

type CreateTourRes struct {
	Result Result `json:"result"`
}
